name: Deploy Automatico Discloud

on:
  push:
    branches:
      - main # Garanta que sua branch no VS Code é a main (se for master, mude aqui)

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Pegando o codigo do GitHub
        uses: actions/checkout@v4

      - name: Enviando para a Discloud
        uses: discloud/deploy-action@v1
        with:
          token: ${{ secrets.DISCLOUD_TOKEN }}