name: Deploy Automatico Discloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Pegando o codigo do GitHub
        uses: actions/checkout@v4

      - name: Configurando o Node.js
        uses: actions/setup-node@v4
        with:
          node-size: 20

      - name: Instalando a Discloud CLI
        run: npm install -g @discloud/cli

      - name: Enviando para a Discloud
        run: discloud commit -t ${{ secrets.DISCLOUD_TOKEN }}